"""Paper 1.16.5 event names for ``Bridge.on`` and server configuration.

Generated from the same event catalog as the Wiki. A constant names an event;
it does not enable forwarding. Configure events.include on the Paper server.
"""


class Events:
    """Fully qualified Java event class names."""

    # block
    ANVIL_DAMAGED = "com.destroystokyo.paper.event.block.AnvilDamagedEvent"
    BEACON_ACTIVATED = "io.papermc.paper.event.block.BeaconActivatedEvent"
    BEACON_DEACTIVATED = "io.papermc.paper.event.block.BeaconDeactivatedEvent"
    BEACON_EFFECT = "com.destroystokyo.paper.event.block.BeaconEffectEvent"
    BELL_REVEAL_RAIDER = "io.papermc.paper.event.block.BellRevealRaiderEvent"
    BELL_RING = "io.papermc.paper.event.block.BellRingEvent"
    BLOCK_BREAK = "org.bukkit.event.block.BlockBreakEvent"
    BLOCK_BURN = "org.bukkit.event.block.BlockBurnEvent"
    BLOCK_CAN_BUILD = "org.bukkit.event.block.BlockCanBuildEvent"
    BLOCK_COOK = "org.bukkit.event.block.BlockCookEvent"
    BLOCK_DAMAGE = "org.bukkit.event.block.BlockDamageEvent"
    BLOCK_DESTROY = "com.destroystokyo.paper.event.block.BlockDestroyEvent"
    BLOCK_DISPENSE = "org.bukkit.event.block.BlockDispenseEvent"
    BLOCK_DISPENSE_ARMOR = "org.bukkit.event.block.BlockDispenseArmorEvent"
    BLOCK_DROP_ITEM = "org.bukkit.event.block.BlockDropItemEvent"
    BLOCK_EXP = "org.bukkit.event.block.BlockExpEvent"
    BLOCK_EXPLODE = "org.bukkit.event.block.BlockExplodeEvent"
    BLOCK_FADE = "org.bukkit.event.block.BlockFadeEvent"
    BLOCK_FAILED_DISPENSE = "io.papermc.paper.event.block.BlockFailedDispenseEvent"
    BLOCK_FERTILIZE = "org.bukkit.event.block.BlockFertilizeEvent"
    BLOCK_FORM = "org.bukkit.event.block.BlockFormEvent"
    BLOCK_FROM_TO = "org.bukkit.event.block.BlockFromToEvent"
    BLOCK_GROW = "org.bukkit.event.block.BlockGrowEvent"
    BLOCK_IGNITE = "org.bukkit.event.block.BlockIgniteEvent"
    BLOCK_MULTI_PLACE = "org.bukkit.event.block.BlockMultiPlaceEvent"
    BLOCK_PHYSICS = "org.bukkit.event.block.BlockPhysicsEvent"
    BLOCK_PISTON_EXTEND = "org.bukkit.event.block.BlockPistonExtendEvent"
    BLOCK_PISTON_RETRACT = "org.bukkit.event.block.BlockPistonRetractEvent"
    BLOCK_PLACE = "org.bukkit.event.block.BlockPlaceEvent"
    BLOCK_PRE_DISPENSE = "io.papermc.paper.event.block.BlockPreDispenseEvent"
    BLOCK_REDSTONE = "org.bukkit.event.block.BlockRedstoneEvent"
    BLOCK_SHEAR_ENTITY = "org.bukkit.event.block.BlockShearEntityEvent"
    BLOCK_SPREAD = "org.bukkit.event.block.BlockSpreadEvent"
    CAULDRON_LEVEL_CHANGE = "org.bukkit.event.block.CauldronLevelChangeEvent"
    DRAGON_EGG_FORM = "io.papermc.paper.event.block.DragonEggFormEvent"
    ENTITY_BLOCK_FORM = "org.bukkit.event.block.EntityBlockFormEvent"
    FLUID_LEVEL_CHANGE = "org.bukkit.event.block.FluidLevelChangeEvent"
    LEAVES_DECAY = "org.bukkit.event.block.LeavesDecayEvent"
    MOISTURE_CHANGE = "org.bukkit.event.block.MoistureChangeEvent"
    NOTE_PLAY = "org.bukkit.event.block.NotePlayEvent"
    PLAYER_SHEAR_BLOCK = "io.papermc.paper.event.block.PlayerShearBlockEvent"
    SIGN_CHANGE = "org.bukkit.event.block.SignChangeEvent"
    SPONGE_ABSORB = "org.bukkit.event.block.SpongeAbsorbEvent"
    TARGET_HIT = "io.papermc.paper.event.block.TargetHitEvent"
    TNT_PRIME = "com.destroystokyo.paper.event.block.TNTPrimeEvent"

    # command
    UNKNOWN_COMMAND = "org.bukkit.event.command.UnknownCommandEvent"

    # enchantment
    ENCHANT_ITEM = "org.bukkit.event.enchantment.EnchantItemEvent"
    PREPARE_ITEM_ENCHANT = "org.bukkit.event.enchantment.PrepareItemEnchantEvent"

    # entity
    AREA_EFFECT_CLOUD_APPLY = "org.bukkit.event.entity.AreaEffectCloudApplyEvent"
    ARROW_BODY_COUNT_CHANGE = "org.bukkit.event.entity.ArrowBodyCountChangeEvent"
    BAT_TOGGLE_SLEEP = "org.bukkit.event.entity.BatToggleSleepEvent"
    CREATURE_SPAWN = "org.bukkit.event.entity.CreatureSpawnEvent"
    CREEPER_IGNITE = "com.destroystokyo.paper.event.entity.CreeperIgniteEvent"
    CREEPER_POWER = "org.bukkit.event.entity.CreeperPowerEvent"
    ELDER_GUARDIAN_APPEARANCE = "io.papermc.paper.event.entity.ElderGuardianAppearanceEvent"
    ENDERMAN_ATTACK_PLAYER = "com.destroystokyo.paper.event.entity.EndermanAttackPlayerEvent"
    ENDERMAN_ESCAPE = "com.destroystokyo.paper.event.entity.EndermanEscapeEvent"
    ENDER_DRAGON_CHANGE_PHASE = "org.bukkit.event.entity.EnderDragonChangePhaseEvent"
    ENDER_DRAGON_FIREBALL_HIT = "com.destroystokyo.paper.event.entity.EnderDragonFireballHitEvent"
    ENDER_DRAGON_FLAME = "com.destroystokyo.paper.event.entity.EnderDragonFlameEvent"
    ENDER_DRAGON_SHOOT_FIREBALL = "com.destroystokyo.paper.event.entity.EnderDragonShootFireballEvent"
    ENTITY_ADD_TO_WORLD = "com.destroystokyo.paper.event.entity.EntityAddToWorldEvent"
    ENTITY_AIR_CHANGE = "org.bukkit.event.entity.EntityAirChangeEvent"
    ENTITY_BREAK_DOOR = "org.bukkit.event.entity.EntityBreakDoorEvent"
    ENTITY_BREED = "org.bukkit.event.entity.EntityBreedEvent"
    ENTITY_CHANGE_BLOCK = "org.bukkit.event.entity.EntityChangeBlockEvent"
    ENTITY_COMBUST = "org.bukkit.event.entity.EntityCombustEvent"
    ENTITY_COMBUST_BY_BLOCK = "org.bukkit.event.entity.EntityCombustByBlockEvent"
    ENTITY_COMBUST_BY_ENTITY = "org.bukkit.event.entity.EntityCombustByEntityEvent"
    ENTITY_CREATE_PORTAL = "org.bukkit.event.entity.EntityCreatePortalEvent"
    ENTITY_DAMAGE = "org.bukkit.event.entity.EntityDamageEvent"
    ENTITY_DAMAGE_BY_BLOCK = "org.bukkit.event.entity.EntityDamageByBlockEvent"
    ENTITY_DAMAGE_BY_ENTITY = "org.bukkit.event.entity.EntityDamageByEntityEvent"
    ENTITY_DEATH = "org.bukkit.event.entity.EntityDeathEvent"
    ENTITY_DROP_ITEM = "org.bukkit.event.entity.EntityDropItemEvent"
    ENTITY_ENTER_BLOCK = "org.bukkit.event.entity.EntityEnterBlockEvent"
    ENTITY_ENTER_LOVE_MODE = "org.bukkit.event.entity.EntityEnterLoveModeEvent"
    ENTITY_EXHAUSTION = "org.bukkit.event.entity.EntityExhaustionEvent"
    ENTITY_EXPLODE = "org.bukkit.event.entity.EntityExplodeEvent"
    ENTITY_INSIDE_BLOCK = "io.papermc.paper.event.entity.EntityInsideBlockEvent"
    ENTITY_INTERACT = "org.bukkit.event.entity.EntityInteractEvent"
    ENTITY_JUMP = "com.destroystokyo.paper.event.entity.EntityJumpEvent"
    ENTITY_KNOCKBACK_BY_ENTITY = "com.destroystokyo.paper.event.entity.EntityKnockbackByEntityEvent"
    ENTITY_LOAD_CROSSBOW = "io.papermc.paper.event.entity.EntityLoadCrossbowEvent"
    ENTITY_MOVE = "io.papermc.paper.event.entity.EntityMoveEvent"
    ENTITY_PATHFIND = "com.destroystokyo.paper.event.entity.EntityPathfindEvent"
    ENTITY_PICKUP_ITEM = "org.bukkit.event.entity.EntityPickupItemEvent"
    ENTITY_PLACE = "org.bukkit.event.entity.EntityPlaceEvent"
    ENTITY_PORTAL = "org.bukkit.event.entity.EntityPortalEvent"
    ENTITY_PORTAL_ENTER = "org.bukkit.event.entity.EntityPortalEnterEvent"
    ENTITY_PORTAL_EXIT = "org.bukkit.event.entity.EntityPortalExitEvent"
    ENTITY_POSE_CHANGE = "org.bukkit.event.entity.EntityPoseChangeEvent"
    ENTITY_POTION_EFFECT = "org.bukkit.event.entity.EntityPotionEffectEvent"
    ENTITY_REGAIN_HEALTH = "org.bukkit.event.entity.EntityRegainHealthEvent"
    ENTITY_REMOVE_FROM_WORLD = "com.destroystokyo.paper.event.entity.EntityRemoveFromWorldEvent"
    ENTITY_RESURRECT = "org.bukkit.event.entity.EntityResurrectEvent"
    ENTITY_SHOOT_BOW = "org.bukkit.event.entity.EntityShootBowEvent"
    ENTITY_SPAWN = "org.bukkit.event.entity.EntitySpawnEvent"
    ENTITY_SPELL_CAST = "org.bukkit.event.entity.EntitySpellCastEvent"
    ENTITY_TAME = "org.bukkit.event.entity.EntityTameEvent"
    ENTITY_TARGET = "org.bukkit.event.entity.EntityTargetEvent"
    ENTITY_TARGET_LIVING_ENTITY = "org.bukkit.event.entity.EntityTargetLivingEntityEvent"
    ENTITY_TELEPORT = "org.bukkit.event.entity.EntityTeleportEvent"
    ENTITY_TELEPORT_END_GATEWAY = "com.destroystokyo.paper.event.entity.EntityTeleportEndGatewayEvent"
    ENTITY_TOGGLE_GLIDE = "org.bukkit.event.entity.EntityToggleGlideEvent"
    ENTITY_TOGGLE_SWIM = "org.bukkit.event.entity.EntityToggleSwimEvent"
    ENTITY_TRANSFORM = "org.bukkit.event.entity.EntityTransformEvent"
    ENTITY_TRANSFORMED = "com.destroystokyo.paper.event.entity.EntityTransformedEvent"
    ENTITY_UNLEASH = "org.bukkit.event.entity.EntityUnleashEvent"
    ENTITY_ZAP = "com.destroystokyo.paper.event.entity.EntityZapEvent"
    EXPERIENCE_ORB_MERGE = "com.destroystokyo.paper.event.entity.ExperienceOrbMergeEvent"
    EXPLOSION_PRIME = "org.bukkit.event.entity.ExplosionPrimeEvent"
    EXP_BOTTLE = "org.bukkit.event.entity.ExpBottleEvent"
    FIREWORK_EXPLODE = "org.bukkit.event.entity.FireworkExplodeEvent"
    FOOD_LEVEL_CHANGE = "org.bukkit.event.entity.FoodLevelChangeEvent"
    HORSE_JUMP = "org.bukkit.event.entity.HorseJumpEvent"
    ITEM_DESPAWN = "org.bukkit.event.entity.ItemDespawnEvent"
    ITEM_MERGE = "org.bukkit.event.entity.ItemMergeEvent"
    ITEM_SPAWN = "org.bukkit.event.entity.ItemSpawnEvent"
    LINGERING_POTION_SPLASH = "org.bukkit.event.entity.LingeringPotionSplashEvent"
    PHANTOM_PRE_SPAWN = "com.destroystokyo.paper.event.entity.PhantomPreSpawnEvent"
    PIGLIN_BARTER = "org.bukkit.event.entity.PiglinBarterEvent"
    PIG_ZAP = "org.bukkit.event.entity.PigZapEvent"
    PIG_ZOMBIE_ANGER = "org.bukkit.event.entity.PigZombieAngerEvent"
    PLAYER_DEATH = "org.bukkit.event.entity.PlayerDeathEvent"
    PLAYER_LEASH_ENTITY = "org.bukkit.event.entity.PlayerLeashEntityEvent"
    PLAYER_NATURALLY_SPAWN_CREATURES = "com.destroystokyo.paper.event.entity.PlayerNaturallySpawnCreaturesEvent"
    POTION_SPLASH = "org.bukkit.event.entity.PotionSplashEvent"
    PRE_CREATURE_SPAWN = "com.destroystokyo.paper.event.entity.PreCreatureSpawnEvent"
    PRE_SPAWNER_SPAWN = "com.destroystokyo.paper.event.entity.PreSpawnerSpawnEvent"
    PROJECTILE_COLLIDE = "com.destroystokyo.paper.event.entity.ProjectileCollideEvent"
    PROJECTILE_HIT = "org.bukkit.event.entity.ProjectileHitEvent"
    PROJECTILE_LAUNCH = "org.bukkit.event.entity.ProjectileLaunchEvent"
    PUFFER_FISH_STATE_CHANGE = "io.papermc.paper.event.entity.PufferFishStateChangeEvent"
    SHEEP_DYE_WOOL = "org.bukkit.event.entity.SheepDyeWoolEvent"
    SHEEP_REGROW_WOOL = "org.bukkit.event.entity.SheepRegrowWoolEvent"
    SKELETON_HORSE_TRAP = "com.destroystokyo.paper.event.entity.SkeletonHorseTrapEvent"
    SLIME_CHANGE_DIRECTION = "com.destroystokyo.paper.event.entity.SlimeChangeDirectionEvent"
    SLIME_PATHFIND = "com.destroystokyo.paper.event.entity.SlimePathfindEvent"
    SLIME_SPLIT = "org.bukkit.event.entity.SlimeSplitEvent"
    SLIME_SWIM = "com.destroystokyo.paper.event.entity.SlimeSwimEvent"
    SLIME_TARGET_LIVING_ENTITY = "com.destroystokyo.paper.event.entity.SlimeTargetLivingEntityEvent"
    SLIME_WANDER = "com.destroystokyo.paper.event.entity.SlimeWanderEvent"
    SPAWNER_SPAWN = "org.bukkit.event.entity.SpawnerSpawnEvent"
    STRIDER_TEMPERATURE_CHANGE = "org.bukkit.event.entity.StriderTemperatureChangeEvent"
    THROWN_EGG_HATCH = "com.destroystokyo.paper.event.entity.ThrownEggHatchEvent"
    TURTLE_GO_HOME = "com.destroystokyo.paper.event.entity.TurtleGoHomeEvent"
    TURTLE_LAY_EGG = "com.destroystokyo.paper.event.entity.TurtleLayEggEvent"
    TURTLE_START_DIGGING = "com.destroystokyo.paper.event.entity.TurtleStartDiggingEvent"
    VILLAGER_ACQUIRE_TRADE = "org.bukkit.event.entity.VillagerAcquireTradeEvent"
    VILLAGER_CAREER_CHANGE = "org.bukkit.event.entity.VillagerCareerChangeEvent"
    VILLAGER_REPLENISH_TRADE = "org.bukkit.event.entity.VillagerReplenishTradeEvent"
    WITCH_CONSUME_POTION = "com.destroystokyo.paper.event.entity.WitchConsumePotionEvent"
    WITCH_READY_POTION = "com.destroystokyo.paper.event.entity.WitchReadyPotionEvent"
    WITCH_THROW_POTION = "com.destroystokyo.paper.event.entity.WitchThrowPotionEvent"

    # hanging
    HANGING_BREAK = "org.bukkit.event.hanging.HangingBreakEvent"
    HANGING_BREAK_BY_ENTITY = "org.bukkit.event.hanging.HangingBreakByEntityEvent"
    HANGING_PLACE = "org.bukkit.event.hanging.HangingPlaceEvent"

    # inventory
    BREW = "org.bukkit.event.inventory.BrewEvent"
    BREWING_STAND_FUEL = "org.bukkit.event.inventory.BrewingStandFuelEvent"
    CRAFT_ITEM = "org.bukkit.event.inventory.CraftItemEvent"
    FURNACE_BURN = "org.bukkit.event.inventory.FurnaceBurnEvent"
    FURNACE_EXTRACT = "org.bukkit.event.inventory.FurnaceExtractEvent"
    FURNACE_SMELT = "org.bukkit.event.inventory.FurnaceSmeltEvent"
    INVENTORY = "org.bukkit.event.inventory.InventoryEvent"
    INVENTORY_CLICK = "org.bukkit.event.inventory.InventoryClickEvent"
    INVENTORY_CLOSE = "org.bukkit.event.inventory.InventoryCloseEvent"
    INVENTORY_CREATIVE = "org.bukkit.event.inventory.InventoryCreativeEvent"
    INVENTORY_DRAG = "org.bukkit.event.inventory.InventoryDragEvent"
    INVENTORY_MOVE_ITEM = "org.bukkit.event.inventory.InventoryMoveItemEvent"
    INVENTORY_OPEN = "org.bukkit.event.inventory.InventoryOpenEvent"
    INVENTORY_PICKUP_ITEM = "org.bukkit.event.inventory.InventoryPickupItemEvent"
    PREPARE_ANVIL = "org.bukkit.event.inventory.PrepareAnvilEvent"
    PREPARE_GRINDSTONE = "com.destroystokyo.paper.event.inventory.PrepareGrindstoneEvent"
    PREPARE_ITEM_CRAFT = "org.bukkit.event.inventory.PrepareItemCraftEvent"
    PREPARE_RESULT = "com.destroystokyo.paper.event.inventory.PrepareResultEvent"
    PREPARE_SMITHING = "org.bukkit.event.inventory.PrepareSmithingEvent"
    SMITH_ITEM = "org.bukkit.event.inventory.SmithItemEvent"
    TRADE_SELECT = "org.bukkit.event.inventory.TradeSelectEvent"

    # packet
    PLAYER_CHUNK_LOAD = "io.papermc.paper.event.packet.PlayerChunkLoadEvent"
    PLAYER_CHUNK_UNLOAD = "io.papermc.paper.event.packet.PlayerChunkUnloadEvent"

    # player
    ASYNC_CHAT = "io.papermc.paper.event.player.AsyncChatEvent"
    ASYNC_PLAYER_CHAT = "org.bukkit.event.player.AsyncPlayerChatEvent"
    ASYNC_PLAYER_PRE_LOGIN = "org.bukkit.event.player.AsyncPlayerPreLoginEvent"
    CHAT = "io.papermc.paper.event.player.ChatEvent"
    ILLEGAL_PACKET = "com.destroystokyo.paper.event.player.IllegalPacketEvent"
    PAPER_PLAYER_LOCALE_CHANGE = "com.destroystokyo.paper.event.player.PlayerLocaleChangeEvent"
    PLAYER_ADVANCEMENT_CRITERION_GRANT = "com.destroystokyo.paper.event.player.PlayerAdvancementCriterionGrantEvent"
    PLAYER_ADVANCEMENT_DONE = "org.bukkit.event.player.PlayerAdvancementDoneEvent"
    PLAYER_ANIMATION = "org.bukkit.event.player.PlayerAnimationEvent"
    PLAYER_ARMOR_CHANGE = "com.destroystokyo.paper.event.player.PlayerArmorChangeEvent"
    PLAYER_ARMOR_STAND_MANIPULATE = "org.bukkit.event.player.PlayerArmorStandManipulateEvent"
    PLAYER_ARM_SWING = "io.papermc.paper.event.player.PlayerArmSwingEvent"
    PLAYER_ATTACK_ENTITY_COOLDOWN_RESET = "com.destroystokyo.paper.event.player.PlayerAttackEntityCooldownResetEvent"
    PLAYER_ATTEMPT_PICKUP_ITEM = "org.bukkit.event.player.PlayerAttemptPickupItemEvent"
    PLAYER_BED_ENTER = "org.bukkit.event.player.PlayerBedEnterEvent"
    PLAYER_BED_FAIL_ENTER = "io.papermc.paper.event.player.PlayerBedFailEnterEvent"
    PLAYER_BED_LEAVE = "org.bukkit.event.player.PlayerBedLeaveEvent"
    PLAYER_BUCKET_EMPTY = "org.bukkit.event.player.PlayerBucketEmptyEvent"
    PLAYER_BUCKET_ENTITY = "org.bukkit.event.player.PlayerBucketEntityEvent"
    PLAYER_BUCKET_FILL = "org.bukkit.event.player.PlayerBucketFillEvent"
    PLAYER_BUCKET_FISH = "org.bukkit.event.player.PlayerBucketFishEvent"
    PLAYER_CHANGED_MAIN_HAND = "org.bukkit.event.player.PlayerChangedMainHandEvent"
    PLAYER_CHANGED_WORLD = "org.bukkit.event.player.PlayerChangedWorldEvent"
    PLAYER_CHANGE_BEACON_EFFECT = "io.papermc.paper.event.player.PlayerChangeBeaconEffectEvent"
    PLAYER_CHAT = "org.bukkit.event.player.PlayerChatEvent"
    PLAYER_CHAT_TAB_COMPLETE = "org.bukkit.event.player.PlayerChatTabCompleteEvent"
    PLAYER_CLIENT_OPTIONS_CHANGE = "com.destroystokyo.paper.event.player.PlayerClientOptionsChangeEvent"
    PLAYER_COMMAND_PREPROCESS = "org.bukkit.event.player.PlayerCommandPreprocessEvent"
    PLAYER_COMMAND_SEND = "org.bukkit.event.player.PlayerCommandSendEvent"
    PLAYER_CONNECTION_CLOSE = "com.destroystokyo.paper.event.player.PlayerConnectionCloseEvent"
    PLAYER_DEEP_SLEEP = "io.papermc.paper.event.player.PlayerDeepSleepEvent"
    PLAYER_DROP_ITEM = "org.bukkit.event.player.PlayerDropItemEvent"
    PLAYER_EDIT_BOOK = "org.bukkit.event.player.PlayerEditBookEvent"
    PLAYER_EGG_THROW = "org.bukkit.event.player.PlayerEggThrowEvent"
    PLAYER_ELYTRA_BOOST = "com.destroystokyo.paper.event.player.PlayerElytraBoostEvent"
    PLAYER_EXP_CHANGE = "org.bukkit.event.player.PlayerExpChangeEvent"
    PLAYER_FISH = "org.bukkit.event.player.PlayerFishEvent"
    PLAYER_FLOWER_POT_MANIPULATE = "io.papermc.paper.event.player.PlayerFlowerPotManipulateEvent"
    PLAYER_GAME_MODE_CHANGE = "org.bukkit.event.player.PlayerGameModeChangeEvent"
    PLAYER_HANDSHAKE = "com.destroystokyo.paper.event.player.PlayerHandshakeEvent"
    PLAYER_HARVEST_BLOCK = "org.bukkit.event.player.PlayerHarvestBlockEvent"
    PLAYER_INITIAL_SPAWN = "com.destroystokyo.paper.event.player.PlayerInitialSpawnEvent"
    PLAYER_INTERACT = "org.bukkit.event.player.PlayerInteractEvent"
    PLAYER_INTERACT_AT_ENTITY = "org.bukkit.event.player.PlayerInteractAtEntityEvent"
    PLAYER_INTERACT_ENTITY = "org.bukkit.event.player.PlayerInteractEntityEvent"
    PLAYER_ITEM_BREAK = "org.bukkit.event.player.PlayerItemBreakEvent"
    PLAYER_ITEM_CONSUME = "org.bukkit.event.player.PlayerItemConsumeEvent"
    PLAYER_ITEM_COOLDOWN = "io.papermc.paper.event.player.PlayerItemCooldownEvent"
    PLAYER_ITEM_DAMAGE = "org.bukkit.event.player.PlayerItemDamageEvent"
    PLAYER_ITEM_HELD = "org.bukkit.event.player.PlayerItemHeldEvent"
    PLAYER_ITEM_MEND = "org.bukkit.event.player.PlayerItemMendEvent"
    PLAYER_JOIN = "org.bukkit.event.player.PlayerJoinEvent"
    PLAYER_JUMP = "com.destroystokyo.paper.event.player.PlayerJumpEvent"
    PLAYER_KICK = "org.bukkit.event.player.PlayerKickEvent"
    PLAYER_LAUNCH_PROJECTILE = "com.destroystokyo.paper.event.player.PlayerLaunchProjectileEvent"
    PLAYER_LECTERN_PAGE_CHANGE = "io.papermc.paper.event.player.PlayerLecternPageChangeEvent"
    PLAYER_LEVEL_CHANGE = "org.bukkit.event.player.PlayerLevelChangeEvent"
    PLAYER_LOCALE_CHANGE = "org.bukkit.event.player.PlayerLocaleChangeEvent"
    PLAYER_LOGIN = "org.bukkit.event.player.PlayerLoginEvent"
    PLAYER_LOOM_PATTERN_SELECT = "io.papermc.paper.event.player.PlayerLoomPatternSelectEvent"
    PLAYER_MOVE = "org.bukkit.event.player.PlayerMoveEvent"
    PLAYER_NAME_ENTITY = "io.papermc.paper.event.player.PlayerNameEntityEvent"
    PLAYER_PICKUP_ARROW = "org.bukkit.event.player.PlayerPickupArrowEvent"
    PLAYER_PICKUP_EXPERIENCE = "com.destroystokyo.paper.event.player.PlayerPickupExperienceEvent"
    PLAYER_PICKUP_ITEM = "org.bukkit.event.player.PlayerPickupItemEvent"
    PLAYER_PORTAL = "org.bukkit.event.player.PlayerPortalEvent"
    PLAYER_POST_RESPAWN = "com.destroystokyo.paper.event.player.PlayerPostRespawnEvent"
    PLAYER_PRE_LOGIN = "org.bukkit.event.player.PlayerPreLoginEvent"
    PLAYER_PURCHASE = "io.papermc.paper.event.player.PlayerPurchaseEvent"
    PLAYER_QUIT = "org.bukkit.event.player.PlayerQuitEvent"
    PLAYER_READY_ARROW = "com.destroystokyo.paper.event.player.PlayerReadyArrowEvent"
    PLAYER_RECIPE_BOOK_CLICK = "com.destroystokyo.paper.event.player.PlayerRecipeBookClickEvent"
    PLAYER_RECIPE_DISCOVER = "org.bukkit.event.player.PlayerRecipeDiscoverEvent"
    PLAYER_REGISTER_CHANNEL = "org.bukkit.event.player.PlayerRegisterChannelEvent"
    PLAYER_RESOURCE_PACK_STATUS = "org.bukkit.event.player.PlayerResourcePackStatusEvent"
    PLAYER_RESPAWN = "org.bukkit.event.player.PlayerRespawnEvent"
    PLAYER_RIPTIDE = "org.bukkit.event.player.PlayerRiptideEvent"
    PLAYER_SHEAR_ENTITY = "org.bukkit.event.player.PlayerShearEntityEvent"
    PLAYER_SIGN_COMMAND_PREPROCESS = "io.papermc.paper.event.player.PlayerSignCommandPreprocessEvent"
    PLAYER_START_SPECTATING_ENTITY = "com.destroystokyo.paper.event.player.PlayerStartSpectatingEntityEvent"
    PLAYER_STATISTIC_INCREMENT = "org.bukkit.event.player.PlayerStatisticIncrementEvent"
    PLAYER_STONECUTTER_RECIPE_SELECT = "io.papermc.paper.event.player.PlayerStonecutterRecipeSelectEvent"
    PLAYER_STOP_SPECTATING_ENTITY = "com.destroystokyo.paper.event.player.PlayerStopSpectatingEntityEvent"
    PLAYER_SWAP_HAND_ITEMS = "org.bukkit.event.player.PlayerSwapHandItemsEvent"
    PLAYER_TAKE_LECTERN_BOOK = "org.bukkit.event.player.PlayerTakeLecternBookEvent"
    PLAYER_TELEPORT = "org.bukkit.event.player.PlayerTeleportEvent"
    PLAYER_TELEPORT_END_GATEWAY = "com.destroystokyo.paper.event.player.PlayerTeleportEndGatewayEvent"
    PLAYER_TOGGLE_FLIGHT = "org.bukkit.event.player.PlayerToggleFlightEvent"
    PLAYER_TOGGLE_SNEAK = "org.bukkit.event.player.PlayerToggleSneakEvent"
    PLAYER_TOGGLE_SPRINT = "org.bukkit.event.player.PlayerToggleSprintEvent"
    PLAYER_TRADE = "io.papermc.paper.event.player.PlayerTradeEvent"
    PLAYER_UNLEASH_ENTITY = "org.bukkit.event.player.PlayerUnleashEntityEvent"
    PLAYER_UNREGISTER_CHANNEL = "org.bukkit.event.player.PlayerUnregisterChannelEvent"
    PLAYER_USE_UNKNOWN_ENTITY = "com.destroystokyo.paper.event.player.PlayerUseUnknownEntityEvent"
    PLAYER_VELOCITY = "org.bukkit.event.player.PlayerVelocityEvent"

    # profile
    FILL_PROFILE = "com.destroystokyo.paper.event.profile.FillProfileEvent"
    LOOKUP_PROFILE = "com.destroystokyo.paper.event.profile.LookupProfileEvent"
    PRE_FILL_PROFILE = "com.destroystokyo.paper.event.profile.PreFillProfileEvent"
    PRE_LOOKUP_PROFILE = "com.destroystokyo.paper.event.profile.PreLookupProfileEvent"
    PROFILE_WHITELIST_VERIFY = "com.destroystokyo.paper.event.profile.ProfileWhitelistVerifyEvent"

    # raid
    RAID_FINISH = "org.bukkit.event.raid.RaidFinishEvent"
    RAID_SPAWN_WAVE = "org.bukkit.event.raid.RaidSpawnWaveEvent"
    RAID_STOP = "org.bukkit.event.raid.RaidStopEvent"
    RAID_TRIGGER = "org.bukkit.event.raid.RaidTriggerEvent"

    # server
    ASYNC_TAB_COMPLETE = "com.destroystokyo.paper.event.server.AsyncTabCompleteEvent"
    BROADCAST_MESSAGE = "org.bukkit.event.server.BroadcastMessageEvent"
    GS4_QUERY = "com.destroystokyo.paper.event.server.GS4QueryEvent"
    MAP_INITIALIZE = "org.bukkit.event.server.MapInitializeEvent"
    PAPER_SERVER_LIST_PING = "com.destroystokyo.paper.event.server.PaperServerListPingEvent"
    PLUGIN_DISABLE = "org.bukkit.event.server.PluginDisableEvent"
    PLUGIN_ENABLE = "org.bukkit.event.server.PluginEnableEvent"
    REMOTE_SERVER_COMMAND = "org.bukkit.event.server.RemoteServerCommandEvent"
    SERVER_COMMAND = "org.bukkit.event.server.ServerCommandEvent"
    SERVER_EXCEPTION = "com.destroystokyo.paper.event.server.ServerExceptionEvent"
    SERVER_LIST_PING = "org.bukkit.event.server.ServerListPingEvent"
    SERVER_LOAD = "org.bukkit.event.server.ServerLoadEvent"
    SERVER_RESOURCES_RELOADED = "io.papermc.paper.event.server.ServerResourcesReloadedEvent"
    SERVER_TICK_END = "com.destroystokyo.paper.event.server.ServerTickEndEvent"
    SERVER_TICK_START = "com.destroystokyo.paper.event.server.ServerTickStartEvent"
    SERVICE_REGISTER = "org.bukkit.event.server.ServiceRegisterEvent"
    SERVICE_UNREGISTER = "org.bukkit.event.server.ServiceUnregisterEvent"
    TAB_COMPLETE = "org.bukkit.event.server.TabCompleteEvent"
    WHITELIST_TOGGLE = "com.destroystokyo.paper.event.server.WhitelistToggleEvent"

    # vehicle
    VEHICLE_BLOCK_COLLISION = "org.bukkit.event.vehicle.VehicleBlockCollisionEvent"
    VEHICLE_CREATE = "org.bukkit.event.vehicle.VehicleCreateEvent"
    VEHICLE_DAMAGE = "org.bukkit.event.vehicle.VehicleDamageEvent"
    VEHICLE_DESTROY = "org.bukkit.event.vehicle.VehicleDestroyEvent"
    VEHICLE_ENTER = "org.bukkit.event.vehicle.VehicleEnterEvent"
    VEHICLE_ENTITY_COLLISION = "org.bukkit.event.vehicle.VehicleEntityCollisionEvent"
    VEHICLE_EXIT = "org.bukkit.event.vehicle.VehicleExitEvent"
    VEHICLE_MOVE = "org.bukkit.event.vehicle.VehicleMoveEvent"
    VEHICLE_UPDATE = "org.bukkit.event.vehicle.VehicleUpdateEvent"

    # weather
    LIGHTNING_STRIKE = "org.bukkit.event.weather.LightningStrikeEvent"
    THUNDER_CHANGE = "org.bukkit.event.weather.ThunderChangeEvent"
    WEATHER_CHANGE = "org.bukkit.event.weather.WeatherChangeEvent"

    # world
    CHUNK_LOAD = "org.bukkit.event.world.ChunkLoadEvent"
    CHUNK_POPULATE = "org.bukkit.event.world.ChunkPopulateEvent"
    CHUNK_UNLOAD = "org.bukkit.event.world.ChunkUnloadEvent"
    LOOT_GENERATE = "org.bukkit.event.world.LootGenerateEvent"
    PORTAL_CREATE = "org.bukkit.event.world.PortalCreateEvent"
    SPAWN_CHANGE = "org.bukkit.event.world.SpawnChangeEvent"
    STRUCTURE_GROW = "org.bukkit.event.world.StructureGrowEvent"
    STRUCTURE_LOCATE = "io.papermc.paper.event.world.StructureLocateEvent"
    TIME_SKIP = "org.bukkit.event.world.TimeSkipEvent"
    WORLD_BORDER_BOUNDS_CHANGE = "io.papermc.paper.event.world.border.WorldBorderBoundsChangeEvent"
    WORLD_BORDER_BOUNDS_CHANGE_FINISH = "io.papermc.paper.event.world.border.WorldBorderBoundsChangeFinishEvent"
    WORLD_BORDER_CENTER_CHANGE = "io.papermc.paper.event.world.border.WorldBorderCenterChangeEvent"
    WORLD_GAME_RULE_CHANGE = "io.papermc.paper.event.world.WorldGameRuleChangeEvent"
    WORLD_INIT = "org.bukkit.event.world.WorldInitEvent"
    WORLD_LOAD = "org.bukkit.event.world.WorldLoadEvent"
    WORLD_SAVE = "org.bukkit.event.world.WorldSaveEvent"
    WORLD_UNLOAD = "org.bukkit.event.world.WorldUnloadEvent"
